const PDFDocument = require('pdfkit');

function generateAgreementPDF(agreement) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('ROOMZY RENTAL AGREEMENT', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Agreement Date: ${new Date(agreement.createdAt).toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).text('PARTIES', { underline: true });
    doc.fontSize(12).text(`Tenant 1: ${agreement.userA.name}`);
    doc.text(`Email: ${agreement.userA.email}`);
    doc.moveDown();
    doc.text(`Tenant 2: ${agreement.userB.name}`);
    doc.text(`Email: ${agreement.userB.email}`);
    doc.moveDown(2);

    doc.fontSize(14).text('RENTAL DETAILS', { underline: true });
    doc.fontSize(12).text(`Monthly Rent: ₹${agreement.rent}`);
    doc.text(`Move-in Date: ${new Date(agreement.moveInDate).toLocaleDateString()}`);
    doc.moveDown();

    doc.text('Rent Split:');
    doc.text(`  - ${agreement.userA.name}: ₹${agreement.rentSplit.userA}`);
    doc.text(`  - ${agreement.userB.name}: ₹${agreement.rentSplit.userB}`);
    doc.moveDown(2);

    if (agreement.rules && agreement.rules.length > 0) {
      doc.fontSize(14).text('HOUSE RULES', { underline: true });
      doc.fontSize(12);
      agreement.rules.forEach((rule, index) => {
        doc.text(`${index + 1}. ${rule}`);
      });
      doc.moveDown(2);
    }

    doc.fontSize(14).text('TERMS & CONDITIONS', { underline: true });
    doc.fontSize(10);
    doc.text('1. Both parties agree to share the premises according to the terms above.');
    doc.text('2. Rent must be paid on or before the 5th of each month.');
    doc.text('3. Either party can terminate with 30 days notice.');
    doc.text('4. Security deposit will be returned at the end of the lease term.');
    doc.moveDown(2);

    doc.fontSize(12).text('SIGNATURES', { underline: true });
    doc.moveDown();
    doc.text(`_________________________     ${agreement.userA.name}`);
    doc.text(`Date: ______________`);
    doc.moveDown();
    doc.text(`_________________________     ${agreement.userB.name}`);
    doc.text(`Date: ______________`);
    doc.moveDown(2);

    doc.fontSize(10).text('Generated by Roomzy', { align: 'center' });

    doc.end();
  });
}

module.exports = { generateAgreementPDF };